[server]
enableStaticServing = true

[theme]
primaryColor = "#1F77B4"
font = "TH Sarabun New"
headingFont = "TH Sarabun New Bold"

[[theme.fontFaces]]
family = "TH Sarabun New"
url = "/static/THSarabunNew.ttf"
weight = 400
style = "normal"

[[theme.fontFaces]]
family = "TH Sarabun New Bold"
url = "/static/THSarabunNewBold.ttf"
weight = 700
style = "normal"
